# Adapted from https://github.com/hogepodge/tvm-docker/blob/main/Dockerfile
FROM nvidia/cuda:11.4.2-devel-ubuntu20.04

# Make apt non-interactive to keep installation from being blocked
ENV DEBIAN_FRONTEND=noninteractive
ENV LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu/:${LD_LIBRARY_PATH}"

# Bring the image up to date
RUN apt-get dist-upgrade -y \
 && apt update -y \
 && apt upgrade -y \
 && apt install -y git screen

ADD config.sh config.sh
ADD apt.txt apt.txt
ADD pip.txt pip.txt

RUN ./config.sh

ENV THREADS=8
